language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: hhvm
    - php: 7.0

before_script:
    - composer self-update
    - composer install --prefer-dist

script: vendor/bin/phpunit

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d5012cfc8f0d8703197b
    on_success: change
    on_failure: always
    on_start: never
