language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: hhvm
    - php: 7.0

before_script:
  - composer self-update
  - composer install --prefer-dist

script:
  - vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml
  - vendor/bin/phpcs --standard=PSR2 ./src/

after_script:
  - php vendor/bin/coveralls -v

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d5012cfc8f0d8703197b
    on_success: change
    on_failure: always
    on_start: never
  hipchat:
    rooms:
      secure: bUyRDatctTHwRPvfrH9Pho5t74R3HAjjczrI0wkukQkriaSOlRKo2hFgheiS7Y0t+Ox0YgJcBPNgpwXzPC75OTg9Vc97UlhWq4JeKXOTp0VTOOwHvJLSARYfC0Wtv0seawLDKpYqVfVc+MvhLNUeNUVtMIAKUl3tRGhNOO5tkh0ntLv9ylcoNVoQLKm0zZAed4tjisv5KVUDG8zUYYVWPbzfEIfi0PCofoYAo4oy94Nuzu8omquOWi4p+vQsaZxzqtJ1f/ac7w8l/ONM8BNflxMAw0tnmBho5dvHiN4pgc5Oilk1omZ7gbvuMI/0kT0Xk0cC1TDJn5qq60BVx+0lD5Fm+dSuFohThnS+DfPTVoegN+ZtRow/cRCcRP1HMBWUSkSLQWTIvJsL+djSix48up57egeH86Ab0lXezr6ti+E9PSzQ2cvVYdLGv4c+2wIFjzRKwgBRq2bSKEjGhjUKDAuJQll9Nh1Eeiou5OOYbmsbrP2G2AJZHD7J4gV/hNHIlqRLodN7/hjlD3eL8yeGmLGDS+LdOywCIztIn9E641imHRZyb2MB5BSBEekHYmuBo5t3Za8yoKsChK/2ofH72uwLkWHmhdcYzEgaTnUJzpvHrD7GmubTdFf5PrBSnkRaJg3IpR4crU4BFyCwbRgM0VdjdoNc5PtEtR3wJNr3I3w=
  slack:
      secure: IGlDYaPzGESdfRcgl5j8Lc65H6bt0y18X5kbGVl8crSXj/M7WgCHb0y/0Plvdm7IoE9NdwhM68ahSh+xYZxa1d466FE7grfr6LalTqCP4hYaCPMjHoI1xKbWZhduIa+1K5ufCeX6BDBIV/WrUaRzZeyV2cu0pejvBJYeVEsdcFFYuQ8ykOg+nc4KQ5OJoa/3jArywMW+0K4048NAtZ9afJmk/nNDGim2b647kyh7g06wurHk8ySOfSncokWDd+qOqrgT98eSnXlgUwIIxN/Bb0gEiN7KQrNcDjBsNtxkKNlSguNNMwfsSf43lgzvC6RzCq2iWwdegLI+jJ3dXMhysqxTo+YHol6z2NZwFV0v/eHJNWWtlEP/IWgv/tMRnG9GZ2T8hRrCvHsRvZpnz/KW8cOExL7pjjOKEhOSCRbluymlTM3pdvr378KiTyQBxWfpGJlXQByTp45h2M4SaBvAZBfuPpppILKWRD8Y/IpV2mRjiDeMbnGS+BfoVfdAwtZfgWpO8eEAAH2OrroRiaGqO4ctkrTsoTr9jVMlMeIFubXPUfOYt6aXplzQQOqeV3lUYZjPsVym6x/ZhZSYMpYm9/yYkvPbcdlSUFNW7f/+IjakYxUh4RCmibX6gzJMxRnlk6eu30FrV2kfHQitDBPNirXmtq0OP00F4wf8vetqTCg=

env:
  global:
    secure: cwoDUvAJNw06z/d38zY8o0Rim880lpqgvbbnpKqus/gVlUF5W5WCmpLaRnj2Z1ZdAL+9rbev+A6ZHfJsKV74Iu5c+rOU7CjIhneA89xOW2Xp/LRXo3SCF7PuTZyRCzaOPYzOMl7NRcri70eqxF9VbZsmhBT7EDglDKX1AVetIFVd6YQDbf/GuBksaiCFrkkQOmTGUdx1zh5YGNoJoe1Cfej5TeT1k19WyJHMNiqVxUcMnipOb//EWJ7+nqwHydBxDEuHAEnrF3C6Lrx4xbURVm7D78IGUtQUlwgJjx8o3Y0er41gD2N+T0UlSSy0+kT00YsIs3xSaEanHTVxooB5FFSA2xr1ivBH+lKBPngRauwIB2l53QIyqPl7xSTZhnmLZI0B9tV7ySXiA2PfM+HwB3Q/5+jxGvQLC3VE7UQAbnCxci+6Z19FGrQUxht3C7moE2rezpsE9oUD4CqlOA+GbhSks2+IeMuXkorL6uijqxNLmRoIcO64jjECLep5el4itheF/oNl5a2QgliNIB6ymO29j3qLke5gl6LiSMqn3RCg0TzocyC2wpGqGkpN0yXiXOF7UdEmLbEKOcS5GnDPk8TPzLnkrmhAJRQ+wZJe2DnYmtvMq0nVyJPicZj8HyfIGp7hpXQBxMx70N0rgSSXNq37m0Vku390xAR5CcST2ZI=
